export const SET_NEW_TOPIC_TITLE = 'SET_NEW_TOPIC_TITLE';
export const CREATE_NEW_TOPIC = 'CREATE_NEW_TOPIC';
export const UPVOTE_TOPIC = 'UPVOTE_TOPIC';
export const DOWNVOTE_TOPIC = 'DOWNVOTE_TOPIC';
